version: '3'

services:
  traefik-proxy:
    image: traefik-proxy
    pull_policy: never
    container_name: traefik-proxy
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    command:
      - --api.insecure=true
      - --providers.docker
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/auto-deploy/certs/https:/etc/traefik/certs
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`traefik.thiagosol.com`)"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.thiagosol.com`)"
      - "traefik.http.routers.traefik-secure.middlewares=traefik-auth@file"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.domains[0].main=thiagosol.com"
      - "traefik.http.routers.traefik-secure.tls.domains[0].sans=traefik.thiagosol.com"
      - "traefik.http.routers.traefik-secure.service=api@internal"
      - "traefik.docker.network=external-sol-apis"
    networks:
      - external-sol-apis
      - logging-network
    deploy:
      resources:
        limits:
          memory: 150M

networks:
  logging-network:
    external: true
  external-sol-apis:
    external: true
